SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 15
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_LIVES = 3
PLAYER_INVINCIBILITY_DURATION = 2.0

SHOT_RADIUS = 5

SCORE_LARGE = 20
SCORE_MEDIUM = 50
SCORE_SMALL = 100

DIFFICULTY_OPTIONS = ["Easy", "Normal", "Hard"]
DIFFICULTY_SETTINGS = {
    "Easy":   {"spawn_rate_mult": 1.5, "speed_mult": 0.7},
    "Normal": {"spawn_rate_mult": 1.0, "speed_mult": 1.0},
    "Hard":   {"spawn_rate_mult": 0.6, "speed_mult": 1.4},
}

HIGHSCORES_FILE = "highscores.md"
